version: 2

builds:
  - env: [CGO_ENABLED=0]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/chay-24/ehz/cmd.version={{.Version}}

brews:
  - repository:
      owner: chay-24
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/chay-24/ehz
    description: CLI for inspecting Strimzi Kafka messages on OpenShift
    license: MIT
    install: |
      bin.install "ehz"
    test: |
      system "#{bin}/ehz", "--version"
